// Theme collections — /blog/podborka/<slug>/ (+ /blog/en/podborka/<slug>/).
// Cards are auto-selected by matching theme keywords against each card's
// description text, so the list stays in sync with the deck data.

export const COLLECTIONS = [
  {
    slug: 'karty-na-lyubov',
    title: 'Карты на любовь и отношения — значения и толкование · Никола Блажен',
    desc: 'Карты про любовь, отношения и близость из трёх колод Никола Блажен: значения, толкование, о чём каждая говорит.',
    seed: 'lyubov',
    h1: 'Карты на любовь и отношения',
    intro: 'Карты, которые говорят о любви, близости, паре, о том, что мешает и что держит вместе. Ниже — те, где эта тема звучит прямо. Для расклада на отношения вытяните одну из них в приложении и задайте открытый вопрос: «что мне важно понять про эти отношения сейчас».',
    kw: ['любов', 'отношени', 'близост', 'партн', 'пара ', 'сердц', 'влюбл', 'нежност', 'объят', 'страст'],
    max: 18,
    titleEn: 'Cards on Love and Relationships — Meanings and Readings · Nikola Blajen',
    descEn: 'Cards about love, relationships, and closeness from the three Nikola Blajen decks: meanings, readings, what each one speaks to.',
    h1En: 'Cards on Love and Relationships',
    introEn: 'Cards that speak about love, closeness, being a couple, what gets in the way and what holds two people together. Below are the ones where this theme comes through directly. For a relationship reading, draw one of these in the app and ask an open question: "what do I need to understand about this relationship right now."',
    kwEn: ['love', 'relationship', 'closeness', 'partner', 'heart', 'romance', 'tenderness', 'embrace', 'passion', 'intimacy'],
  },
  {
    slug: 'karty-na-dengi',
    title: 'Карты на деньги и достаток — значения и толкование · Никола Блажен',
    desc: 'Карты про деньги, достаток, изобилие и работу с финансами из трёх колод Никола Блажен: значения и толкование.',
    seed: 'dengi',
    h1: 'Карты на деньги и достаток',
    intro: 'Карты про деньги, изобилие, работу и то, что закрывает или открывает поток. Не «когда разбогатею», а «что мне сейчас мешает» и «куда направить силы». Вытяните одну в приложении с таким вопросом.',
    kw: ['деньг', 'достат', 'изобил', 'богат', 'финанс', 'ресурс', 'благосостоян', 'нищ', 'бедн', 'заработ'],
    max: 16,
    titleEn: 'Cards on Money and Abundance — Meanings and Readings · Nikola Blajen',
    descEn: 'Cards about money, abundance, and working with your finances from the three Nikola Blajen decks: meanings and readings.',
    h1En: 'Cards on Money and Abundance',
    introEn: 'Cards about money, abundance, work, and what closes or opens the flow. Not "when will I get rich" but "what\'s in my way right now" and "where to put my effort." Draw one in the app with that question.',
    kwEn: ['money', 'abundance', 'wealth', 'financ', 'resource', 'prosperity', 'poverty', 'earn', 'income', 'riches'],
  },
  {
    slug: 'karty-na-rabotu-i-delo',
    title: 'Карты на работу, дело и предназначение — значения · Никола Блажен',
    desc: 'Карты про работу, своё дело, реализацию и предназначение из трёх колод Никола Блажен: значения и толкование.',
    seed: 'rabota',
    h1: 'Карты на работу и дело',
    intro: 'Карты про труд, своё дело, реализацию, предназначение и выбор пути. Полезны, когда стоишь на развилке или выгорел. Вопрос к карте: «на что смотреть в этой ситуации с работой».',
    kw: ['работ', 'дел', 'труд', 'предназначен', 'реализ', 'призван', 'карьер', 'проект', 'мастер', 'творч', 'служен'],
    max: 16,
    titleEn: 'Cards on Work, Purpose and Calling — Meanings · Nikola Blajen',
    descEn: 'Cards about work, your own path, fulfillment, and purpose from the three Nikola Blajen decks: meanings and readings.',
    h1En: 'Cards on Work and Purpose',
    introEn: 'Cards about labor, your own path, fulfillment, calling, and choosing a direction. Useful when you\'re at a crossroads or burned out. Question for the card: "what should I look at in this work situation."',
    kwEn: ['work', 'career', 'purpose', 'calling', 'fulfillment', 'project', 'craft', 'creativ', 'service', 'labor', 'vocation'],
  },
  {
    slug: 'karty-na-strahi-i-trevogu',
    title: 'Карты про страх, тревогу и сомнения — значения · Никола Блажен',
    desc: 'Карты про страх, тревогу, сомнения и то, как с ними обходиться — из трёх колод Никола Блажен.',
    seed: 'strahi',
    h1: 'Карты про страх и тревогу',
    intro: 'Карты, которые прямо говорят о страхе, тревоге, сомнении и внутреннем сопротивлении — и о том, как через это проходить. Не чтобы напугать, а чтобы посмотреть туда, куда обычно не смотришь.',
    kw: ['страх', 'трево', 'сомнен', 'паник', 'боязн', 'стресс', 'напряжен', 'беспокой', 'опасен', 'пугает'],
    max: 16,
    titleEn: 'Cards on Fear, Anxiety and Doubt — Meanings · Nikola Blajen',
    descEn: 'Cards about fear, anxiety, doubt, and how to work through them — from the three Nikola Blajen decks.',
    h1En: 'Cards on Fear and Anxiety',
    introEn: 'Cards that speak directly about fear, anxiety, doubt, and inner resistance — and how to move through it. Not to scare you, but to help you look where you usually don\'t.',
    kwEn: ['fear', 'anxiet', 'doubt', 'panic', 'stress', 'worry', 'tension', 'afraid', 'danger', 'frighten'],
  },
  {
    slug: 'karty-na-peremeny-i-vybor',
    title: 'Карты на перемены, выбор и новый этап — значения · Никола Блажен',
    desc: 'Карты про перемены, выбор, новый этап и завершение старого — из трёх колод Никола Блажен: значения и толкование.',
    seed: 'peremeny',
    h1: 'Карты на перемены и выбор',
    intro: 'Карты про развилки, перемены, завершение старого и начало нового. Когда надо решиться или отпустить. Вопрос к карте: «какой шаг будет честным».',
    kw: ['перемен', 'выбор', 'решен', 'этап', 'начал', 'заверш', 'путь', 'дорог', 'поворот', 'новое ', 'изменен', 'переход'],
    max: 18,
    titleEn: 'Cards on Change and Choice — Meanings · Nikola Blajen',
    descEn: 'Cards about change, choice, a new stage, and letting go of the old — from the three Nikola Blajen decks: meanings and readings.',
    h1En: 'Cards on Change and Choice',
    introEn: 'Cards about crossroads, change, ending the old and starting the new. For when you need to decide or let go. Question for the card: "what would an honest step look like."',
    kwEn: ['change', 'choice', 'decision', 'new stage', 'beginning', 'ending', 'transition', 'path', 'turning point', 'transform'],
  },
  {
    slug: 'karty-na-silu-i-sebya',
    title: 'Карты на внутреннюю силу и опору на себя — значения · Никола Блажен',
    desc: 'Карты про внутреннюю силу, стержень, опору на себя и самоценность — из трёх колод Никола Блажен.',
    seed: 'sila',
    h1: 'Карты на внутреннюю силу',
    intro: 'Карты про стержень, опору на себя, достоинство и способность выстоять. Для моментов, когда нужно вспомнить, из чего ты сделан.',
    kw: ['сил', 'стерж', 'опор', 'достоинств', 'ценност', 'вера в себя', 'уверенн', 'воля', 'дух', 'выстоя', 'стойк', 'самооцен'],
    max: 16,
    titleEn: 'Cards on Inner Strength and Self-Reliance — Meanings · Nikola Blajen',
    descEn: 'Cards about inner strength, an inner core, self-reliance, and self-worth — from the three Nikola Blajen decks.',
    h1En: 'Cards on Inner Strength',
    introEn: 'Cards about your inner core, self-reliance, dignity, and the ability to hold your ground. For moments when you need to remember what you\'re made of.',
    kwEn: ['strength', 'inner core', 'self-relian', 'dignity', 'self-worth', 'confiden', 'willpower', 'spirit', 'resilien', 'stand your ground'],
  },
]
